from building import *
Import("SOC")

cwd     = GetCurrentDir()
src     = Split('''
common/rkadk_media_comm.c
common/rkadk_signal.c
common/rkadk_thread.c
common/rkadk_version.c
common/rkadk_log.c
param/rkadk_param_map.c
param/rkadk_param.c
param/rkadk_struct2ini.c
third-party/iniparser/dictionary.c
third-party/iniparser/iniparser.c
''')

if GetDepend('RT_RKADK_ENABLE_COMMON_FUNCTIONS'):
    src += ['common/rkadk_msg.c']
    src += ['common/rkadk_thumb_comm.c']
    src += ['audio/encoder/rkadk_audio_encoder_mp3.c']
    src += ['audio/encoder/rkadk_audio_encoder.c']
    src += ['muxer/rkadk_muxer.c']
    src += ['record/rkadk_record.c']
    src += ['photo/rkadk_photo.c']
    src += ['stream/rkadk_stream.c']
    src += ['live/rtsp/rkadk_rtsp.c']
    src += ['osd/rkadk_osd.c.c']
    src += ['live/rtmp/rkadk_rtmp.c']

if GetDepend('RT_RKADK_ENABLE_AOV'):
    src += ['aov/rkadk_aov.c']

if GetDepend('RT_RKADK_ENABLE_STORAGE'):
    src += ['storage/rkadk_storage.c']

if GetDepend('RT_RKADK_ENABLE_DISPLAY'):
    src += ['ui/rkadk_ui.c']
    src += ['display/rkadk_disp.c']

if GetDepend('RT_RKADK_ENABLE_PLAYER'):
    src += ['audio/decoder/rkadk_audio_decoder_mp3.c']
    src += ['audio/decoder/rkadk_audio_decoder.c']
    src += ['demuxer/rkadk_demuxer.c']
    src += ['player/rkadk_player.c']

CPPPATH = [cwd]
CPPPATH += ["../../libc/posix/pthreads"]
CPPPATH += ["../../libc/posix/io/man/sys"]
CPPPATH += ["../../libc/posix/io/poll"]
CPPPATH += ["../include"]
CPPPATH += ["../../../externel/common_algorithm/misc/include"]
CPPPATH += ["../../../externel/rockit/sdk/include"]
CPPPATH += ["./common"]
CPPPATH += ["./third-party"]
CPPPATH += ["./audio/decoder"]

CPPDEFINES = ['OS_RTT']
libs = ['librkdemuxer']
libs += ['librkaudio']
libs += ['librockit']

libpath = [cwd + '/../../common_algorithm/misc/lib/arm-none-eabi']

if SOC == 'RK3308':
    CPPPATH += ["../../rockit/sdk/lib/arm/rk3308"]
    libpath1 = [cwd + '/../../rockit/mpi/sdk/lib/arm/rk3308/rtt']

if SOC == 'RK3506':
    CPPPATH += ["../../rockit/sdk/lib/arm/rk3506"]
    libpath1 = [cwd + '/../../rockit/mpi/sdk/lib/arm/rk3506/rtt']


group = DefineGroup('rkadk', src, depend = ['RT_USING_RKADK'], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES, LIBS = libs, LIBPATH = libpath + libpath1)
# group = DefineGroup('rkadk', src, depend = ['RT_USING_RKADK'], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')